### ISSUE TITLE
Volume buttons are not working in call

### ISSUE THREAD

**Issue by MrCyjaneK** [droidian/meta#2]
When being in call I can't use volume buttons to change volume, but I am able to change it in the settings. (Same thing happened on ubuntu touch)

**Comment by erikinkinen** [comment]
Volume levels would have to be connected to oFono which manages the call audio volume.

**Comment by g7** [comment]
voice call audio is actually exposed by pulseaudio-modules-droid (if `voice_virtual_stream` is enabled).

This series of commits (sorry for the spam, there was a bug in the build infra that made that unbuildable :rofl: ) adds support for detecting those in libgnome-volume-control, and then allows changing the call volume both from phosh and gsd-media-keys. The commit descriptions have more details.

There still are some rough edges to this implementation - Android HAL exposes six "steps" for voice call volume, but we instead have a whole 0-100% range. On some HALs, setting to 0 doesn't even mute the output (like on qx1000).

But still, will probably return to it later. Current implementation is a nice improvement compared to what we had before ;)

Will close this once it hits production.

**Comment by g7** [comment]
Landing in production as we speak, closing :)
